<?php
/**
 * SessionIdentityManagerTest class file.
 */

declare( strict_types = 1 );

namespace Automattic\WooCommerce\Tests\Internal\FraudProtectionPlugin\Sessions;

use Automattic\WooCommerce\FraudProtection\Tests\FraudProtectionUnitTestCase;
use Automattic\WooCommerce\Internal\FraudProtectionPlugin\Sessions\SessionIdentityManager;

/**
 * Tests for SessionIdentityManager.
 *
 * @covers \Automattic\WooCommerce\Internal\FraudProtectionPlugin\Sessions\SessionIdentityManager
 */
class SessionIdentityManagerTest extends FraudProtectionUnitTestCase {

	/** An identity in the format the plugin generates. */
	private const VALID_IDENTITY = '0123456789abcdef0123456789abcdef';

	/** Another identity in the format the plugin generates. */
	private const OTHER_VALID_IDENTITY = 'fedcba9876543210fedcba9876543210';

	/** Format of identities generated by the plugin. */
	private const GENERATED_IDENTITY_PATTERN = '/\A[a-f0-9]{32}\z/';

	/**
	 * The System Under Test.
	 *
	 * @var SessionIdentityManager
	 */
	private $sut;

	/**
	 * The session handler in place before the test, restored in tearDown().
	 *
	 * @var \WC_Session|null
	 */
	private $original_session;

	/**
	 * The cookies in place before the test, restored in tearDown().
	 *
	 * @var array<string, mixed>
	 */
	private array $original_cookies;

	/**
	 * Runs before each test.
	 */
	public function setUp(): void {
		parent::setUp();

		$this->original_session = WC()->session;
		$this->original_cookies = $_COOKIE;
		unset( $_COOKIE[ SessionIdentityManager::IDENTITY_COOKIE_NAME ], $_COOKIE['tk_ai'] );

		WC()->session = new \WC_Session_Handler();
		WC()->session->init();

		$this->sut = new SessionIdentityManager();
	}

	/**
	 * Runs after each test.
	 */
	public function tearDown(): void {
		remove_filter( 'woocommerce_set_cookie_options', array( $this->sut, 'add_identity_cookie_same_site' ), 10 );
		WC()->session = $this->original_session;
		$_COOKIE      = $this->original_cookies;
		parent::tearDown();
	}

	/**
	 * @testdox Generates a new identity in the plugin format when neither the cookie nor the session has one.
	 */
	public function test_get_identity_id_generates_identity_when_none_exists(): void {
		$result = $this->sut->get_identity_id();

		$this->assertMatchesRegularExpression( self::GENERATED_IDENTITY_PATTERN, $result, 'A new identity should have the generated format' );
		$this->assertSame( $result, $_COOKIE[ SessionIdentityManager::IDENTITY_COOKIE_NAME ] ?? null, 'The new identity should be set as the cookie value' ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- The test asserts the raw cookie value.
	}

	/**
	 * @testdox Persists the identity to the session for future use.
	 */
	public function test_get_identity_id_persists_identity_to_session(): void {
		$result = $this->sut->get_identity_id();

		$this->assertSame( $result, WC()->session->get( SessionIdentityManager::CUSTOMER_IDENTITY_ID_KEY ), 'The identity should be persisted to the session' );
	}

	/**
	 * @testdox Returns the same identity on subsequent calls.
	 */
	public function test_get_identity_id_returns_consistent_value(): void {
		$first_call  = $this->sut->get_identity_id();
		$second_call = $this->sut->get_identity_id();

		$this->assertSame( $first_call, $second_call, 'Subsequent calls should return the same identity' );
	}

	/**
	 * @testdox Uses a valid identity from the cookie and stores it in the session.
	 */
	public function test_get_identity_id_uses_cookie_identity(): void {
		$_COOKIE[ SessionIdentityManager::IDENTITY_COOKIE_NAME ] = self::VALID_IDENTITY;

		$result = $this->sut->get_identity_id();

		$this->assertSame( self::VALID_IDENTITY, $result );
		$this->assertSame( self::VALID_IDENTITY, WC()->session->get( SessionIdentityManager::CUSTOMER_IDENTITY_ID_KEY ) );
	}

	/**
	 * @testdox A valid cookie identity wins over a different identity stored in the session.
	 */
	public function test_get_identity_id_prefers_cookie_over_session(): void {
		$_COOKIE[ SessionIdentityManager::IDENTITY_COOKIE_NAME ] = self::VALID_IDENTITY;
		WC()->session->set( SessionIdentityManager::CUSTOMER_IDENTITY_ID_KEY, self::OTHER_VALID_IDENTITY );

		$result = $this->sut->get_identity_id();

		$this->assertSame( self::VALID_IDENTITY, $result, 'The cookie identity should win' );
		$this->assertSame( self::VALID_IDENTITY, WC()->session->get( SessionIdentityManager::CUSTOMER_IDENTITY_ID_KEY ), 'The session should be updated with the cookie identity' );
	}

	/**
	 * @testdox Reuses a valid session identity and sets it as the cookie value when the cookie is missing.
	 */
	public function test_get_identity_id_reuses_session_identity_without_cookie(): void {
		WC()->session->set( SessionIdentityManager::CUSTOMER_IDENTITY_ID_KEY, self::VALID_IDENTITY );

		$result = $this->sut->get_identity_id();

		$this->assertSame( self::VALID_IDENTITY, $result );
		$this->assertSame( self::VALID_IDENTITY, $_COOKIE[ SessionIdentityManager::IDENTITY_COOKIE_NAME ] ?? null ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- The test asserts the raw cookie value.
	}

	/**
	 * @testdox Ignores a cookie value that the plugin did not generate.
	 * @dataProvider unrecognized_identity_provider
	 *
	 * @param mixed $value Cookie value.
	 */
	public function test_get_identity_id_ignores_unrecognized_cookie_value( mixed $value ): void {
		$_COOKIE[ SessionIdentityManager::IDENTITY_COOKIE_NAME ] = $value;
		WC()->session->set( SessionIdentityManager::CUSTOMER_IDENTITY_ID_KEY, self::VALID_IDENTITY );

		$result = $this->sut->get_identity_id();

		$this->assertSame( self::VALID_IDENTITY, $result, 'The valid session identity should be used' );
		$this->assertSame( self::VALID_IDENTITY, $_COOKIE[ SessionIdentityManager::IDENTITY_COOKIE_NAME ], 'The cookie value should be replaced' ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- The test asserts the raw cookie value.
	}

	/**
	 * @testdox Replaces a session value that the plugin did not generate in the current format.
	 * @dataProvider unrecognized_identity_provider
	 *
	 * @param mixed $value Session value.
	 */
	public function test_get_identity_id_replaces_unrecognized_session_value( mixed $value ): void {
		WC()->session->set( SessionIdentityManager::CUSTOMER_IDENTITY_ID_KEY, $value );

		$result = $this->sut->get_identity_id();

		$this->assertNotSame( $value, $result );
		$this->assertMatchesRegularExpression( self::GENERATED_IDENTITY_PATTERN, $result );
		$this->assertSame( $result, WC()->session->get( SessionIdentityManager::CUSTOMER_IDENTITY_ID_KEY ) );
	}

	/**
	 * Values that the plugin does not accept as an identity.
	 *
	 * @return array<string, array{mixed}>
	 */
	public function unrecognized_identity_provider(): array {
		return array(
			'Tracks anonymous ID'    => array( 'abcdefghijklmnopqrstuvwx' ),
			'WordPress.com user ID'  => array( '123456' ),
			'legacy fallback'        => array( 'customer_0123456789abcdef0123456789abcdef' ),
			'uppercase hex'          => array( strtoupper( self::VALID_IDENTITY ) ),
			'too long'               => array( self::VALID_IDENTITY . '0' ),
			'trailing newline'       => array( self::VALID_IDENTITY . "\n" ),
			'empty value'            => array( '' ),
			'integer'                => array( 123456 ),
			'unsupported array type' => array( array( self::VALID_IDENTITY ) ),
		);
	}

	/**
	 * @testdox Does not use the Tracks cookie as the identity.
	 */
	public function test_get_identity_id_ignores_tracks_cookie(): void {
		$_COOKIE['tk_ai'] = self::VALID_IDENTITY;

		$result = $this->sut->get_identity_id();

		$this->assertNotSame( self::VALID_IDENTITY, $result );
		$this->assertMatchesRegularExpression( self::GENERATED_IDENTITY_PATTERN, $result );
	}

	/**
	 * @testdox Initializes the session and returns a valid identity when the session is not available.
	 */
	public function test_get_identity_id_initializes_session_when_unavailable(): void {
		// @phpstan-ignore assign.propertyType
		WC()->session = null;

		$result = $this->sut->get_identity_id();

		$this->assertMatchesRegularExpression( self::GENERATED_IDENTITY_PATTERN, $result, 'Should return a valid identity even when the session was not initially available' );
		// @phpstan-ignore method.impossibleType
		$this->assertInstanceOf( \WC_Session::class, WC()->session, 'Session should be initialized after the call' );
	}

	/**
	 * @testdox Returns the cookie settings that the browser script uses.
	 */
	public function test_get_identity_cookie_settings(): void {
		$this->assertSame(
			array(
				'name'   => 'wfp_id',
				'path'   => COOKIEPATH ? COOKIEPATH : '/',
				'domain' => COOKIE_DOMAIN ? COOKIE_DOMAIN : '',
			),
			$this->sut->get_identity_cookie_settings()
		);
	}

	/**
	 * @testdox Registered hooks add SameSite=Lax to the options of the identity cookie.
	 */
	public function test_register_adds_same_site_to_identity_cookie_options(): void {
		$this->sut->register();
		$options = array(
			'expires' => 0,
			'path'    => '/',
		);

		// phpcs:ignore WooCommerce.Commenting.CommentHooks.MissingHookComment -- Test invokes the hook.
		$result = apply_filters( 'woocommerce_set_cookie_options', $options, SessionIdentityManager::IDENTITY_COOKIE_NAME, self::VALID_IDENTITY );

		$this->assertSame( array_merge( $options, array( 'samesite' => 'Lax' ) ), $result );
	}

	/**
	 * @testdox Registered hooks leave cookie options unchanged when they do not belong to the identity cookie or already set SameSite.
	 * @dataProvider unchanged_cookie_options_provider
	 *
	 * @param mixed $options Cookie options.
	 * @param mixed $name    Cookie name.
	 */
	public function test_register_leaves_other_cookie_options_unchanged( mixed $options, mixed $name ): void {
		$this->sut->register();

		// phpcs:ignore WooCommerce.Commenting.CommentHooks.MissingHookComment -- Test invokes the hook.
		$this->assertSame( $options, apply_filters( 'woocommerce_set_cookie_options', $options, $name, self::VALID_IDENTITY ) );
	}

	/**
	 * Cookie options that must not receive the identity cookie's SameSite value.
	 *
	 * @return array<string, array{mixed, mixed}>
	 */
	public function unchanged_cookie_options_provider(): array {
		return array(
			'another cookie'        => array( array( 'path' => '/' ), 'woocommerce_items_in_cart' ),
			'SameSite already set'  => array( array( 'samesite' => 'Strict' ), SessionIdentityManager::IDENTITY_COOKIE_NAME ),
			'options are not array' => array( 'invalid', SessionIdentityManager::IDENTITY_COOKIE_NAME ),
		);
	}
}
