<?php
/**
 * SessionIdentityManager class file.
 */

declare( strict_types=1 );

namespace Automattic\WooCommerce\Internal\FraudProtectionPlugin\Sessions;

defined( 'ABSPATH' ) || exit;

/**
 * Manages the customer identity ID persisted in the WooCommerce session.
 *
 * The identity ID correlates fraud protection events and log entries for a
 * browser across requests. It is stored in a dedicated session cookie, which
 * the Blackbox init script reads or creates in the browser, and mirrored in
 * the WC session for reuse. The cookie wins when it holds a valid identity.
 */
class SessionIdentityManager {

	/** Maximum stored identity length in bytes. */
	private const MAX_IDENTITY_LENGTH = 255;

	/** Format of identities generated by the plugin, both here and in the Blackbox init script. */
	private const GENERATED_IDENTITY_PATTERN = '/\A[a-f0-9]{32}\z/';

	/**
	 * Session key for storing customer identity ID.
	 */
	public const CUSTOMER_IDENTITY_ID_KEY = '_fraud_protection_customer_identity_id';

	/**
	 * Name of the cookie that holds the identity ID.
	 */
	public const IDENTITY_COOKIE_NAME = 'wfp_id';

	/**
	 * Register hooks.
	 *
	 * @return void
	 */
	public function register(): void {
		// wc_setcookie() has no SameSite argument.
		add_filter( 'woocommerce_set_cookie_options', array( $this, 'add_identity_cookie_same_site' ), 10, 2 );
	}

	/**
	 * Ensure cart and session are available.
	 *
	 * Loads cart if not already loaded, which initializes session for both
	 * traditional (cookie) and Store API (token) flows.
	 *
	 * @return void
	 */
	public function ensure_cart_loaded(): void {
		if ( ! did_action( 'woocommerce_load_cart_from_session' ) && function_exists( 'wc_load_cart' ) ) {
			WC()->call_function( 'wc_load_cart' );
		}
	}

	/**
	 * Check if WooCommerce session is available.
	 *
	 * @return bool True if session is available.
	 */
	private function is_session_available(): bool {
		$this->ensure_cart_loaded();
		return WC()->session instanceof \WC_Session;
	}

	/**
	 * Get a unique identifier for the current browser session.
	 *
	 * A valid identity in the cookie wins. Otherwise a valid identity stored in
	 * the WC session is reused, or a new one is generated, and the cookie is set
	 * so that the browser reports the same identity. Values that the plugin did
	 * not generate in the current format are ignored.
	 *
	 * @return string Session identifier.
	 */
	public function get_identity_id(): string {
		if ( ! $this->is_session_available() ) {
			WC()->initialize_session();
		}

		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Validated against a strict pattern.
		$identity_id = self::validate_generated_identity_id( wp_unslash( $_COOKIE[ self::IDENTITY_COOKIE_NAME ] ?? null ) );
		if ( null === $identity_id ) {
			$identity_id = self::validate_generated_identity_id( WC()->session->get( self::CUSTOMER_IDENTITY_ID_KEY ) ) ?? bin2hex( random_bytes( 16 ) );
			$this->set_identity_cookie( $identity_id );
		}

		// Persists the identity ID in the session for future use.
		WC()->session->set( self::CUSTOMER_IDENTITY_ID_KEY, $identity_id );

		return $identity_id;
	}

	/**
	 * Get the cookie settings that the Blackbox init script uses to read or create the identity cookie.
	 *
	 * The settings are the same for every visitor, so pages that include them remain cacheable.
	 *
	 * @return array{name: string, path: string, domain: string} Cookie settings.
	 */
	public function get_identity_cookie_settings(): array {
		return array(
			'name'   => self::IDENTITY_COOKIE_NAME,
			'path'   => COOKIEPATH ? COOKIEPATH : '/',
			'domain' => COOKIE_DOMAIN ? COOKIE_DOMAIN : '',
		);
	}

	/**
	 * Set the identity cookie for the current browser session.
	 *
	 * The cookie expires with the browser session, stays readable by the
	 * Blackbox init script, and uses SameSite=Lax like the cookie that the
	 * script creates.
	 *
	 * @param string $identity_id Identity ID.
	 * @return void
	 */
	private function set_identity_cookie( string $identity_id ): void {
		$_COOKIE[ self::IDENTITY_COOKIE_NAME ] = $identity_id;

		if ( headers_sent() ) {
			return;
		}

		wc_setcookie( self::IDENTITY_COOKIE_NAME, $identity_id, 0, is_ssl(), false );
	}

	/**
	 * Add SameSite=Lax to the identity cookie options unless the site already set a SameSite value.
	 *
	 * @internal
	 *
	 * @param mixed $options Cookie options passed to setcookie().
	 * @param mixed $name    Cookie name.
	 * @return mixed The options, with SameSite added for the identity cookie.
	 */
	public function add_identity_cookie_same_site( mixed $options, mixed $name ): mixed {
		if ( self::IDENTITY_COOKIE_NAME !== $name || ! is_array( $options ) || isset( $options['samesite'] ) ) {
			return $options;
		}

		$options['samesite'] = 'Lax';

		return $options;
	}

	/**
	 * Validate an identity generated by the plugin.
	 *
	 * @param mixed $identity_id Identity value.
	 * @return string|null The identity, or null when it does not have the generated format.
	 */
	private static function validate_generated_identity_id( mixed $identity_id ): ?string {
		return is_string( $identity_id ) && 1 === preg_match( self::GENERATED_IDENTITY_PATTERN, $identity_id ) ? $identity_id : null;
	}

	/**
	 * Normalize an identity value for storage and logging.
	 *
	 * @param mixed $identity_id Identity value.
	 * @return string|null Normalized identity, or null when rejected.
	 */
	public static function normalize_identity_id( mixed $identity_id ): ?string {
		if ( is_int( $identity_id ) ) {
			$identity_id = (string) $identity_id;
		}

		if ( ! is_string( $identity_id ) || '' === $identity_id || 1 !== preg_match( '/\A[A-Za-z0-9:_+\/=\-]+\z/', $identity_id ) ) {
			return null;
		}

		return substr( $identity_id, 0, self::MAX_IDENTITY_LENGTH );
	}
}
